version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 10
    assignees:
      - 'Awhux'
    commit-message:
      include: 'scope'

  - package-ecosystem: 'npm'
    directory: '/apps/api'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 10
    assignees:
      - 'Awhux'
    commit-message:
      include: 'scope'

  - package-ecosystem: 'npm'
    directory: '/apps/app'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 10
    assignees:
      - 'Awhux'
    commit-message:
      include: 'scope'

  - package-ecosystem: 'npm'
    directory: '/packages/database'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 10
    assignees:
      - 'Awhux'
    commit-message:
      include: 'scope'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 5
    assignees:
      - 'Awhux'
    commit-message:
      include: 'scope'
